### ISSUE TITLE
Keep the name as Warpinator

### ISSUE THREAD

**Issue by gjsman** [linuxmint/warp#11]
I firmly believe that this project should retain it's current testing name as Warpinator.

Warpinator is a unique name, is unlikely to get confused with other projects, and it's a great [Phineas and Ferb](https://phineasandferb.fandom.com/wiki/List_of_Doofenshmirtz%27s_schemes_and_inventions) reference. What's not to love?

**Comment by elahn** [comment]
LANdo Transferian

**Comment by svastian99** [comment]
MintShare
LM connect / LM share
Conecta {connect in spanish}
Me2U file share / Me2U port
Direct file tray
Swift-share LAN

**Comment by svastian99** [comment]
MintShare
LM connect / LM share
Conecta {connect in spanish}
Me2U file share / Me2U port
Direct file tray
Swift-share LAN

**Comment by dadoprom** [comment]
Warpinator is perfect, do not change it please...

**Comment by gjsman** [comment]
I am personally tired about all of these "XYZShare" or "XYZ Connect" apps on all Operating Systems. Even within Linux, we've got "KDE Connect," "MConnect," "GSConnect," etc. Labelling your app "Connect" doesn't tell the user anything about what other "Connect" apps are compatible. Everybody seems to have an app named "Connect" these days: Android, Windows, Samsung... and yet, they don't have high adoption because "Connect" tells the user nothing as to what they are actually compatible with.

I don't support a simplistic name like "Files" or "File Sharing." Let's say you have Linux Mint and want to share a file with a Ubuntu or non-Mint user. With Warpinator, you just tell the other person to install Warpinator, and you're good. No other program uses Warpinator, and it has a name that is memorable enough to stick with minimal odds of conflict. With "File Sharing," well... where do you start looking? Is Linux Mint File Sharing really fully compatible Ubuntu File Sharing or Fedora File Sharing or Mac File Sharing or Windows File Sharing? And as for names with "LM" or "Linux Mint" in the name, this ruins the vendor-neutrality of the software and gives the impression that it is only for Linux Mint users. 

I also _strongly **do not**_ support having LM in the name for the fear that Linux Mint could end up like KDE, where every program has to start with a K. I mean, from Wikipedia: KAppTemplate, Kate, KBugBuster, KCachegrind, KDESvn, KDevelop, KDiff3, Kommander, Konquerer, KGeography, KHangMan, KBibTeX, KGrab, Krita, Kontact, Kopete, KTorrent, KBluetooth, Konsole, KWallet, KCalc, Kaffeine, K3B, Kdenlive, Kontact, it just goes on and on. I personally believe this also hurts KDE's adoption by new users. If you are a new user not used to Linux, having every program start with a K is pretty bewildering. Just imagine having every program on your computer, for consistency's sake, beginning with LM instead. LMSettings, LMTorrent, LMPDF, LMShare, LMConnect... bad. Right now, we have the X-apps project in which several apps start with X. Having LM would be kind of inconsistent. Why not Xwarpinator or even Xarpinator?

Conecta? I mean, it sounds OK, but what happens when we make a Spanish translation? Should we use the English word for Connect ("Connect") within Spanish locales and "Conecta" in English locales? If we use "Conecta" within Spanish locales, that sounds a lot like the connection tools in a variety of distributions and even other Operating Systems (Win, Mac), and is pretty hard to search online.

"Direct File Tray": I'm not a fan. This isn't really a tray as it is a full GUI app.
"Swift-share LAN": Sounds cool, but how many people know what LAN actually means? Even for those who know, it almost sounds like a networking tool instead of a file-sharing tool.

I think that the most successful file-sharing apps tend to have the most unique names. Apple, for example, uses AirDrop. AirDrop works on Macs and iOS devices (and only on those devices), and market penetration for AirDrop appears to be the highest for any fast-file-sharing method. Linux servers and MacOS devices have this awesome tool available called ["Magic Wormhole"](https://www.github.com/warner/magic-wormhole) which works _amazingly_, even though it is only a CLI app. Magic Wormhole, AirDrop, Warpinator, unique and even slightly ridiculous names that get attention and help customers remember that functionality. So far, looking at other products, the more unique the name, the more popular the feature is. The less unique the name (e.g. "Samsung Connect"), the less well-known and popular the feature is.

**Comment by ghumphr1** [comment]
I agree with this ethos .. warpinator is a great name .. that’s why I’m watching it from a non mint distro..


Sent from Yahoo Mail for iPad


On Wednesday, April 1, 2020, 4:47 AM, gjsman <notifications@github.com> wrote:




I am personally tired about all of these "XYZShare" or "XYZ Connect" apps on all Operating Systems. Even within Linux, we've got "KDE Connect," "MConnect," "GSConnect," etc. Labelling your app "Connect" doesn't tell the user anything about what other "Connect" apps are compatible. Everybody seems to have an app named "Connect" these days: Android, Windows, Samsung... and yet, they don't have high adoption because "Connect" tells the user nothing as to what they are actually compatible with.

I don't support a simplistic name like "Files" or "File Sharing." Let's say you have Linux Mint and want to share a file with a Ubuntu or non-Mint user. With Warpinator, you just tell the other person to install Warpinator, and you're good. No other program uses Warpinator, and it has a name that is memorable enough to stick with minimal odds of conflict. With "File Sharing," well... where do you start looking? Is Linux Mint File Sharing really fully compatible Ubuntu File Sharing or Fedora File Sharing or Mac File Sharing or Windows File Sharing? And as for names with "LM" or "Linux Mint" in the name, this ruins the vendor-neutrality of the software and gives the impression that it is only for Linux Mint users.

I also strongly do not support having LM in the name for the fear that Linux Mint could end up like KDE, where every program has to start with a K. I mean, from Wikipedia: KAppTemplate, Kate, KBugBuster, KCachegrind, KDESvn, KDevelop, KDiff3, Kommander, Konquerer, KGeography, KHangMan, KBibTeX, KGrab, Krita, Kontact, Kopete, KTorrent, KBluetooth, Konsole, KWallet, KCalc, Kaffeine, K3B, Kdenlive, Kontact, it just goes on and on. I personally believe this also hurts KDE's adoption by new users. If you are a new user not used to Linux, having every program start with a K is pretty bewildering. Just imagine having every program on your computer, for consistency's sake, beginning with LM instead. LMSettings, LMTorrent, LMPDF, LMShare, LMConnect... bad. Right now, we have the X-apps project in which several apps start with X. Having LM would be kind of inconsistent. Why not Xwarpinator or even Xarpinator?

Conecta? I mean, it sounds OK, but what happens when we make a Spanish translation? Should we use the English word for Connect ("Connect") within Spanish locales and "Conecta" in English locales? If we use "Conecta" within Spanish locales, that sounds a lot like the connection tools in a variety of distributions and even other Operating Systems (Win, Mac), and is pretty hard to search online.

"Direct File Tray": I'm not a fan. This isn't really a tray as it is a full GUI app.
"Swift-share LAN": Sounds cool, but how many people know what LAN actually means? Even for those who know, it almost sounds like a networking tool instead of a file-sharing tool.

I think that the most successful file-sharing apps tend to have the most unique names. Apple, for example, uses AirDrop. AirDrop works on Macs and iOS devices (and only on those devices), and market penetration for AirDrop appears to be the highest for any fast-file-sharing method. Linux servers and MacOS devices have this awesome tool available called "Magic Wormhole" which works amazingly, even though it is only a CLI app. Magic Wormhole, AirDrop, Warpinator, unique and even slightly ridiculous names that get attention and help customers remember that functionality. So far, looking at other products, the more unique the name, the more popular the feature is. The less unique the name (e.g. "Samsung Connect"), the less well-known and popular the feature is.

**Comment by AndrewCRichards** [comment]
I suggest "dumbwaiter" for the name:
> a small elevator, manually or electrically operated, consisting typically of a box with shelves, used in apartment houses, restaurants, and large private dwellings for moving dishes, food, garbage, etc., between floors. [dictionary.com definition]

...so quite a good metaphor for what this application does.

**Comment by gjsman** [comment]
@AndrewCRichards I don't know what nationality you are from, but in the US, nobody knows or uses the term "dumbwaiter." Furthermore, if you say it, it immediately suggests "dumb waiter," or "dumb restaurant server," which is very confusing. (I have lived in the US since birth and have never heard the term used.)

**Comment by solodyagin** [comment]
I'm confused .. war - война, pinator - пинатель? =) Warp, hmm...

**Comment by ParaDice13** [comment]
How about _Catch!_ instead of Warpinator? It's supposed to be a quick-and-easy file transfer tool on the local network. Let's have the name stress that it's just as easy as throwing an object across the room.

**Comment by danielp96** [comment]
As a spanish speaking linux mint user I oppose using "conecta" as a name. It sounds cool in english, but in spanish sounds like mispronouncing a normal word.

I too oppose using any Mint, LM, etc. prefix, suffix or whatever in the name. It implies it's specific to the distro and will fall in whta KDE does as previously mentioned.

Generic names is in my opinion a grave mistake, like what gnome does, it's difficuilt to search information for something like that and everyone ends up calling it along the lines of "Gnome Web" for example, it loses its uniqness and gives the sense of being a component of something else.

Warpinator sounds good in both spanish and english, it's catchy and unique. It should be kept as it's name.

**Comment by mtwebster** [comment]
It's going to be Warpinator so closing this :)
