### ISSUE TITLE
Runtime dependency versions do not allow installation on Debian Buster

### ISSUE THREAD

**Issue by SwampRabbit** [linuxmint/warp#9]
I packaged a .deb with pbuilder to test, everything went fine, but...

The following are current dependency versions available in Debian Buster which stop installation at this time:
python3-xapp (1.2.0-2)
gir1.2-xapp-1.0 (1.2.2-1) < also dependencies libxapp1 and libxapps-common

The versions in Debian Bullseye are high enough though, I assume it wasn't caught because LDME and Ubuntu 20.04 are as well.

~~Once I install the Bullseye versions, I run into #4~~ < believe this is fixed now

**Comment by mtwebster** [comment]
There's nothing we can do with buster - there are quite a number of things we had to do for LMDE 4 (based on buster) so everything would work.  I'm not sure of the timeline for why 1.6 didn't make it in in time, but as far as I know it would be impossible to fix now due to Debian's update policies.  Note: we have no input on Debian packaging of our stuff, and do not participate (other than some collaboration with the maintainers).
